export type MCQ = {
  id: string;
  courseCode: string; // e.g. "ARAB150", "CPEG220"
  question: string;
  choices: string[];
  correctIndex: number;
  explanation?: string;
};

export const QUESTION_BANK: MCQ[] = [
  /* ============================== ARAB150 (20) ============================== */
  {
    id: "arab150-1",
    courseCode: "ARAB150",
    question: "In human development, “capabilities” refers mainly to:",
    choices: [
      "Government spending only",
      "People’s real freedoms to live the life they value",
      "Total exports of a country",
      "Population size",
    ],
    correctIndex: 1,
  },
  {
    id: "arab150-2",
    courseCode: "ARAB150",
    question: "Which is most closely tied to improving life expectancy?",
    choices: [
      "Higher inflation",
      "Access to basic healthcare",
      "Higher interest rates",
      "More tourism ads",
    ],
    correctIndex: 1,
  },
  {
    id: "arab150-3",
    courseCode: "ARAB150",
    question: "Human development differs from economic growth because it focuses on:",
    choices: [
      "GDP only",
      "People’s wellbeing and opportunities",
      "Currency exchange rates",
      "Stock market performance",
    ],
    correctIndex: 1,
  },
  {
    id: "arab150-4",
    courseCode: "ARAB150",
    question: "A common indicator used in development comparisons is:",
    choices: [
      "HDI-like composite index",
      "Only football ranking",
      "Only rainfall",
      "Only land area",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-5",
    courseCode: "ARAB150",
    question: "Which factor most directly raises educational attainment?",
    choices: [
      "School access and quality",
      "Higher oil prices automatically",
      "More deserts",
      "More highways only",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-6",
    courseCode: "ARAB150",
    question: "“Youth unemployment” can strongly impact development by:",
    choices: [
      "Reducing social stability and future productivity",
      "Guaranteeing higher innovation",
      "Lowering education demand always",
      "Eliminating migration",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-7",
    courseCode: "ARAB150",
    question: "A policy that directly targets poverty reduction is:",
    choices: [
      "Conditional cash transfers to low-income families",
      "Raising luxury taxes only",
      "Increasing advertising budgets",
      "Reducing vaccination programs",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-8",
    courseCode: "ARAB150",
    question: "Gender equality matters for development mainly because it:",
    choices: [
      "Only improves sports outcomes",
      "Expands participation in education and labor markets",
      "Reduces literacy",
      "Makes prices higher",
    ],
    correctIndex: 1,
  },
  {
    id: "arab150-9",
    courseCode: "ARAB150",
    question: "A “demographic dividend” happens when:",
    choices: [
      "Working-age population grows relative to dependents",
      "Birth rates rise forever",
      "Everyone retires earlier",
      "Population becomes zero",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-10",
    courseCode: "ARAB150",
    question: "Which is an example of “social protection”?",
    choices: [
      "Pensions and unemployment insurance",
      "Only building airports",
      "Only importing food",
      "Only sports clubs",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-11",
    courseCode: "ARAB150",
    question: "Improving “institutional quality” often means:",
    choices: [
      "Stronger rule of law and transparency",
      "More sand extraction",
      "Lower literacy",
      "Fewer public services",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-12",
    courseCode: "ARAB150",
    question: "Which is most likely to reduce child mortality?",
    choices: [
      "Vaccination programs",
      "Higher car imports",
      "More TV shows",
      "Lower school enrollment",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-13",
    courseCode: "ARAB150",
    question: "“Brain drain” can harm development when:",
    choices: [
      "Skilled workers permanently leave without knowledge transfer",
      "More people learn languages",
      "Tourism increases",
      "Schools improve",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-14",
    courseCode: "ARAB150",
    question: "Urbanization can support development if it is accompanied by:",
    choices: [
      "Jobs, housing, and infrastructure planning",
      "No public transport",
      "Banning education",
      "Reducing healthcare access",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-15",
    courseCode: "ARAB150",
    question: "“Food security” is best described as:",
    choices: [
      "Stable access to sufficient nutritious food",
      "Only local cuisine popularity",
      "Only export volume",
      "Only restaurant counts",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-16",
    courseCode: "ARAB150",
    question: "Environmental sustainability matters for development because it:",
    choices: [
      "Protects resources and health for future generations",
      "Always lowers productivity",
      "Eliminates education needs",
      "Only affects tourism",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-17",
    courseCode: "ARAB150",
    question: "Income inequality can reduce human development by:",
    choices: [
      "Limiting access to health/education for lower-income groups",
      "Increasing trust in institutions always",
      "Guaranteeing lower crime",
      "Raising literacy automatically",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-18",
    courseCode: "ARAB150",
    question: "A strong sign of improved governance is:",
    choices: [
      "Accountability and effective public service delivery",
      "Higher humidity",
      "More traffic",
      "Lower school attendance",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-19",
    courseCode: "ARAB150",
    question: "Which is most aligned with “inclusive growth”?",
    choices: [
      "Growth that benefits broad segments of society",
      "Growth only for one sector",
      "Growth with lower education",
      "Growth with higher disease rates",
    ],
    correctIndex: 0,
  },
  {
    id: "arab150-20",
    courseCode: "ARAB150",
    question: "A key benefit of investing in early childhood education is:",
    choices: [
      "Better long-term learning and health outcomes",
      "Lower literacy",
      "Higher dropout rates",
      "Less workforce participation",
    ],
    correctIndex: 0,
  },

  /* ============================== ARAB205 (20) ============================== */
  {
    id: "arab205-1",
    courseCode: "ARAB205",
    question: "In the early Islamic period, the “caliphate” refers to:",
    choices: [
      "A trade route",
      "A political leadership institution",
      "A poetic genre",
      "A currency system only",
    ],
    correctIndex: 1,
  },
  {
    id: "arab205-2",
    courseCode: "ARAB205",
    question: "A major function of historical “bazaars/souqs” was:",
    choices: [
      "Only worship",
      "Trade and social exchange",
      "Only farming",
      "Only military training",
    ],
    correctIndex: 1,
  },
  {
    id: "arab205-3",
    courseCode: "ARAB205",
    question: "Arabic’s role in civilization was significant because it became:",
    choices: [
      "A shared language for scholarship and administration",
      "Only a spoken dialect with no writing",
      "Used only for poetry",
      "Only a regional slang",
    ],
    correctIndex: 0,
  },
  {
    id: "arab205-4",
    courseCode: "ARAB205",
    question: "“Translation movements” historically helped by:",
    choices: [
      "Transferring scientific/philosophical knowledge across cultures",
      "Banning education",
      "Ending trade",
      "Eliminating libraries",
    ],
    correctIndex: 0,
  },
  {
    id: "arab205-5",
    courseCode: "ARAB205",
    question: "A “waqf” is best described as:",
    choices: [
      "A military unit",
      "An endowment for public/religious benefit",
      "A type of ship",
      "A tax on imports only",
    ],
    correctIndex: 1,
  },
  {
    id: "arab205-6",
    courseCode: "ARAB205",
    question: "Islamic civilization’s urban development often featured:",
    choices: [
      "Public markets and mosques integrated into city life",
      "No public institutions",
      "Only farms",
      "Only castles",
    ],
    correctIndex: 0,
  },
  {
    id: "arab205-7",
    courseCode: "ARAB205",
    question: "A “madrasa” historically refers to:",
    choices: ["A hospital", "An educational institution", "A port", "A bank"],
    correctIndex: 1,
  },
  {
    id: "arab205-8",
    courseCode: "ARAB205",
    question: "“Islamic art” is diverse; one common feature is:",
    choices: [
      "Use of geometry/calligraphy as major elements",
      "Only portraits",
      "Only sculptures of rulers",
      "No pattern work at all",
    ],
    correctIndex: 0,
  },
  {
    id: "arab205-9",
    courseCode: "ARAB205",
    question: "The term “umma” generally refers to:",
    choices: ["A marketplace", "A community of believers", "A library", "A palace"],
    correctIndex: 1,
  },
  {
    id: "arab205-10",
    courseCode: "ARAB205",
    question: "Trade across the Indian Ocean historically connected:",
    choices: [
      "East Africa, Arabia, South Asia, and beyond",
      "Only Europe and America",
      "Only one city",
      "Only deserts",
    ],
    correctIndex: 0,
  },
  {
    id: "arab205-11",
    courseCode: "ARAB205",
    question: "Historical chronicles are important because they:",
    choices: [
      "Provide narratives and perspectives on events (with bias to evaluate)",
      "Are always perfectly objective",
      "Replace archaeology completely",
      "Contain only math",
    ],
    correctIndex: 0,
  },
  {
    id: "arab205-12",
    courseCode: "ARAB205",
    question: "“Fiqh” is most accurately described as:",
    choices: [
      "A building style",
      "Jurisprudence/understanding of law",
      "A musical instrument",
      "A trade guild",
    ],
    correctIndex: 1,
  },
  {
    id: "arab205-13",
    courseCode: "ARAB205",
    question: "A key driver for cultural exchange in history was:",
    choices: ["Isolation", "Trade and travel networks", "No literacy", "No migration"],
    correctIndex: 1,
  },
  {
    id: "arab205-14",
    courseCode: "ARAB205",
    question: "A “primary source” is:",
    choices: [
      "A later textbook summary",
      "An original artifact/document from the time studied",
      "A fictional novel always",
      "A random blog post",
    ],
    correctIndex: 1,
  },
  {
    id: "arab205-15",
    courseCode: "ARAB205",
    question: "Why do historians compare multiple sources?",
    choices: [
      "To confirm reliability and understand differing viewpoints",
      "To make stories shorter",
      "To avoid evidence",
      "To remove context",
    ],
    correctIndex: 0,
  },
  {
    id: "arab205-16",
    courseCode: "ARAB205",
    question: "A common role of libraries and book culture historically was:",
    choices: [
      "Preserving and spreading knowledge",
      "Destroying education",
      "Stopping translation",
      "Ending literacy",
    ],
    correctIndex: 0,
  },
  {
    id: "arab205-17",
    courseCode: "ARAB205",
    question: "Calligraphy in Arab-Islamic civilization often functioned as:",
    choices: [
      "A purely random decoration",
      "A major artistic and cultural expression",
      "Only numbers",
      "Only maps",
    ],
    correctIndex: 1,
  },
  {
    id: "arab205-18",
    courseCode: "ARAB205",
    question: "“Cultural continuity” means:",
    choices: [
      "No changes across time",
      "Some practices/ideas persist even as societies evolve",
      "All societies are identical",
      "History repeats exactly",
    ],
    correctIndex: 1,
  },
  {
    id: "arab205-19",
    courseCode: "ARAB205",
    question: "A balanced historical argument should mainly use:",
    choices: [
      "Evidence + reasoning",
      "Only opinions",
      "Only memes",
      "Only one quote with no analysis",
    ],
    correctIndex: 0,
  },
  {
    id: "arab205-20",
    courseCode: "ARAB205",
    question: "Studying civilization surveys is useful because it helps:",
    choices: [
      "Connect political, social, economic, and cultural factors together",
      "Ignore context",
      "Avoid sources",
      "Focus only on dates with no meaning",
    ],
    correctIndex: 0,
  },

  /* ============================== ARAB215 (20) ============================== */
  {
    id: "arab215-1",
    courseCode: "ARAB215",
    question: "A strong thesis statement should be:",
    choices: [
      "A vague topic",
      "An arguable claim that guides the essay",
      "A random quote with no explanation",
      "A list of unrelated facts",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-2",
    courseCode: "ARAB215",
    question: "In academic writing, a paragraph is usually best built around:",
    choices: ["One main idea", "Five unrelated ideas", "Only questions", "Only metaphors"],
    correctIndex: 0,
  },
  {
    id: "arab215-3",
    courseCode: "ARAB215",
    question: "A “topic sentence” typically:",
    choices: [
      "Ends the essay",
      "Introduces the paragraph’s main point",
      "Repeats the title only",
      "Is always a quote",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-4",
    courseCode: "ARAB215",
    question: "Good transitions in writing help to:",
    choices: [
      "Confuse the reader",
      "Show logical connections between ideas",
      "Replace evidence",
      "Avoid structure",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-5",
    courseCode: "ARAB215",
    question: "Which is the best example of a claim needing evidence?",
    choices: [
      "My favorite color is blue",
      "This policy improved literacy rates",
      "I like coffee",
      "I feel happy today",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-6",
    courseCode: "ARAB215",
    question: "A conclusion should typically:",
    choices: [
      "Introduce a completely new argument",
      "Restate the thesis and synthesize key points",
      "Only repeat the introduction word-for-word",
      "End abruptly with no summary",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-7",
    courseCode: "ARAB215",
    question: "The strongest evidence in an essay is usually:",
    choices: [
      "Personal insults",
      "Relevant facts/quotes with analysis",
      "Random examples",
      "Unverified rumors",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-8",
    courseCode: "ARAB215",
    question: "When paraphrasing, you should:",
    choices: [
      "Copy the original exactly",
      "Rewrite in your own words and still cite the source",
      "Change only one word",
      "Avoid citations",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-9",
    courseCode: "ARAB215",
    question: "A coherent essay structure is best described as:",
    choices: [
      "Random points",
      "Introduction → body arguments → conclusion",
      "Only conclusion",
      "Only bullet points",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-10",
    courseCode: "ARAB215",
    question: "Which is a hallmark of clear writing?",
    choices: [
      "Long sentences with no punctuation",
      "Precise vocabulary and direct sentences",
      "No paragraphs",
      "No verbs",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-11",
    courseCode: "ARAB215",
    question: "In persuasive writing, a counterargument is:",
    choices: [
      "A personal attack",
      "An opposing viewpoint you address fairly",
      "A summary of the title",
      "A typo",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-12",
    courseCode: "ARAB215",
    question: "Good academic tone is usually:",
    choices: [
      "Aggressive and insulting",
      "Clear, respectful, and evidence-based",
      "Only jokes",
      "Only slang",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-13",
    courseCode: "ARAB215",
    question: "A revision pass should focus most on:",
    choices: [
      "Only font choice",
      "Meaning, structure, and clarity",
      "Only word count",
      "Only emojis",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-14",
    courseCode: "ARAB215",
    question: "Which sentence is the best topic sentence?",
    choices: [
      "There are many things in life.",
      "This essay discusses stuff.",
      "Social media influences study habits by changing attention patterns and time use.",
      "I will write about social media.",
    ],
    correctIndex: 2,
  },
  {
    id: "arab215-15",
    courseCode: "ARAB215",
    question: "A strong paragraph is most likely to include:",
    choices: [
      "A claim + evidence + explanation",
      "Only evidence with no claim",
      "Only claim with no evidence",
      "Only a quote",
    ],
    correctIndex: 0,
  },
  {
    id: "arab215-16",
    courseCode: "ARAB215",
    question: "Which is the best purpose of an introduction?",
    choices: [
      "Hide the topic",
      "Provide context and present the thesis",
      "Repeat the conclusion",
      "List references only",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-17",
    courseCode: "ARAB215",
    question: "Clarity improves when you:",
    choices: [
      "Use undefined pronouns constantly",
      "Use specific nouns and avoid unnecessary repetition",
      "Avoid punctuation",
      "Use only passive voice",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-18",
    courseCode: "ARAB215",
    question: "A citation is mainly used to:",
    choices: [
      "Make text longer",
      "Give credit and allow verification",
      "Replace evidence",
      "Avoid responsibility",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-19",
    courseCode: "ARAB215",
    question: "Which is the best revision strategy?",
    choices: [
      "Edit while writing the first sentence",
      "Do a separate pass for structure, then language",
      "Never re-read your work",
      "Only check spelling",
    ],
    correctIndex: 1,
  },
  {
    id: "arab215-20",
    courseCode: "ARAB215",
    question: "A well-supported claim is one that is:",
    choices: [
      "Based on evidence and explained logically",
      "Purely emotional",
      "Random",
      "Copied with no analysis",
    ],
    correctIndex: 0,
  },

  /* ============================== CPEG220 (20) ============================== */
  {
    id: "cpeg220-1",
    courseCode: "CPEG220",
    question: "The CPU component that performs arithmetic/logic operations is the:",
    choices: ["ALU", "Cache", "Register file only", "DMA controller"],
    correctIndex: 0,
  },
  {
    id: "cpeg220-2",
    courseCode: "CPEG220",
    question: "A register is typically used to:",
    choices: [
      "Store temporary values very quickly",
      "Store data permanently",
      "Replace the hard disk",
      "Send internet packets",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-3",
    courseCode: "CPEG220",
    question: "The program counter (PC) holds:",
    choices: [
      "The current instruction address",
      "The last data value",
      "The stack base only",
      "The CPU temperature",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-4",
    courseCode: "CPEG220",
    question: "Cache memory mainly improves performance by:",
    choices: [
      "Reducing average memory access time",
      "Increasing disk capacity",
      "Reducing instruction set size",
      "Replacing the ALU",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-5",
    courseCode: "CPEG220",
    question: "A “pipeline hazard” is a situation that:",
    choices: [
      "Prevents correct/efficient pipelined execution",
      "Guarantees speedup always",
      "Removes need for branching",
      "Eliminates memory",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-6",
    courseCode: "CPEG220",
    question: "A data hazard often occurs when:",
    choices: [
      "An instruction depends on the result of a previous instruction",
      "Power is removed",
      "A keyboard is unplugged",
      "A monitor is off",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-7",
    courseCode: "CPEG220",
    question: "Branch prediction is used to:",
    choices: [
      "Reduce pipeline stalls caused by branches",
      "Increase RAM size",
      "Encrypt memory",
      "Change instruction opcode formats",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-8",
    courseCode: "CPEG220",
    question: "RISC architectures are generally characterized by:",
    choices: [
      "Simple instructions and typically fixed-length formats",
      "Very complex single instructions",
      "No registers",
      "Only microcode with no assembly",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-9",
    courseCode: "CPEG220",
    question: "CISC architectures are generally characterized by:",
    choices: [
      "More complex instructions and often variable-length formats",
      "Only fixed-length instructions",
      "No addressing modes",
      "No stack operations",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-10",
    courseCode: "CPEG220",
    question: "A bus is best described as:",
    choices: [
      "A shared communication pathway for data/address/control signals",
      "A CPU register type",
      "A file system format",
      "A logic gate",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-11",
    courseCode: "CPEG220",
    question: "Main memory (RAM) is typically:",
    choices: ["Volatile", "Non-volatile", "Optical", "Magnetic tape"],
    correctIndex: 0,
  },
  {
    id: "cpeg220-12",
    courseCode: "CPEG220",
    question: "In a 32-bit address space, the maximum addressable memory is:",
    choices: ["4 GB", "32 GB", "2 GB", "128 GB"],
    correctIndex: 0,
  },
  {
    id: "cpeg220-13",
    courseCode: "CPEG220",
    question: "Big-endian means the:",
    choices: [
      "Most significant byte is stored at the lowest address",
      "Least significant byte is stored at the lowest address",
      "CPU uses only 8-bit operations",
      "Stack grows upward always",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-14",
    courseCode: "CPEG220",
    question: "Little-endian means the:",
    choices: [
      "Least significant byte is stored at the lowest address",
      "Most significant byte is stored at the lowest address",
      "Only signed numbers are allowed",
      "No bytes exist",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-15",
    courseCode: "CPEG220",
    question: "The stack is commonly used for:",
    choices: [
      "Function calls and local variables",
      "Storing video frames only",
      "Ethernet routing",
      "GPU shaders",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-16",
    courseCode: "CPEG220",
    question: "An interrupt is best described as:",
    choices: [
      "A signal that temporarily halts normal execution to service an event",
      "A permanent CPU failure",
      "A method to increase clock speed",
      "A type of cache block",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-17",
    courseCode: "CPEG220",
    question: "DMA is useful because it:",
    choices: [
      "Allows peripherals to transfer data to memory with minimal CPU involvement",
      "Eliminates memory",
      "Disables interrupts",
      "Forces slower transfers",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-18",
    courseCode: "CPEG220",
    question: "The instruction cycle generally includes:",
    choices: [
      "Fetch, decode, execute (and write-back)",
      "Only execute",
      "Only decode",
      "Only fetch",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-19",
    courseCode: "CPEG220",
    question: "A control unit is responsible for:",
    choices: [
      "Generating control signals to coordinate CPU operations",
      "Doing floating-point math only",
      "Storing files",
      "Power supply regulation",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg220-20",
    courseCode: "CPEG220",
    question: "The “von Neumann bottleneck” refers to:",
    choices: [
      "Limited throughput between CPU and memory",
      "Too many CPU registers",
      "Infinite cache speed",
      "No instruction fetch stage",
    ],
    correctIndex: 0,
  },

  /* ============================== CPEG330 (20) ============================== */
  {
    id: "cpeg330-1",
    courseCode: "CPEG330",
    question: "A microcontroller typically integrates:",
    choices: ["CPU + memory + peripherals on one chip", "Only RAM", "Only GPU", "Only hard disk"],
    correctIndex: 0,
  },
  {
    id: "cpeg330-2",
    courseCode: "CPEG330",
    question: "GPIO pins are used for:",
    choices: [
      "General-purpose digital input/output",
      "Only analog output",
      "Only networking",
      "Only video",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg330-3",
    courseCode: "CPEG330",
    question: "An ADC is used to:",
    choices: [
      "Convert analog signals to digital values",
      "Convert digital to analog",
      "Increase clock speed",
      "Encrypt data",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg330-4",
    courseCode: "CPEG330",
    question: "A DAC is used to:",
    choices: [
      "Convert digital values to analog signals",
      "Convert analog to digital",
      "Count interrupts",
      "Cache instructions",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg330-5",
    courseCode: "CPEG330",
    question: "I2C typically uses how many signal lines?",
    choices: ["1", "2", "4", "8"],
    correctIndex: 1,
    explanation: "SDA + SCL.",
  },
  {
    id: "cpeg330-6",
    courseCode: "CPEG330",
    question: "SPI typically includes:",
    choices: ["SCLK, MOSI, MISO, CS", "Only TX/RX", "Only SDA/SCL", "Only one wire"],
    correctIndex: 0,
  },
  {
    id: "cpeg330-7",
    courseCode: "CPEG330",
    question: "UART communication is typically:",
    choices: ["Asynchronous serial", "Synchronous parallel", "Optical only", "Analog only"],
    correctIndex: 0,
  },
  {
    id: "cpeg330-8",
    courseCode: "CPEG330",
    question: "A timer peripheral is commonly used for:",
    choices: [
      "Delays, periodic interrupts, PWM generation",
      "Storing images",
      "Wi-Fi routing",
      "File compression",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg330-9",
    courseCode: "CPEG330",
    question: "PWM is useful for controlling:",
    choices: [
      "Motor speed / LED brightness",
      "RAM size",
      "CPU instruction set",
      "Ethernet MAC address",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg330-10",
    courseCode: "CPEG330",
    question: "An interrupt service routine (ISR) should generally be:",
    choices: [
      "Short and fast",
      "Very long and blocking",
      "Full of delays",
      "Always allocate large memory",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg330-11",
    courseCode: "CPEG330",
    question: "Debouncing is needed for:",
    choices: ["Mechanical switches", "Crystal oscillators", "SRAM chips", "LCD backlights"],
    correctIndex: 0,
  },
  {
    id: "cpeg330-12",
    courseCode: "CPEG330",
    question: "Memory-mapped I/O means peripherals are accessed:",
    choices: [
      "Using normal load/store addresses",
      "Only via USB",
      "Only via file system",
      "Only via cloud APIs",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg330-13",
    courseCode: "CPEG330",
    question: "A pull-up resistor is used to:",
    choices: [
      "Prevent a floating input by biasing it high",
      "Increase current to infinity",
      "Convert analog to digital",
      "Boost CPU frequency",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg330-14",
    courseCode: "CPEG330",
    question: "Why are decoupling capacitors placed near IC power pins?",
    choices: [
      "To reduce supply noise and stabilize voltage during switching",
      "To increase wire length",
      "To slow the CPU by design",
      "To store program code",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg330-15",
    courseCode: "CPEG330",
    question: "An external interrupt pin is typically used for:",
    choices: [
      "Detecting external events (button/sensor edge)",
      "Storing data",
      "Rendering graphics",
      "Cooling control only",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg330-16",
    courseCode: "CPEG330",
    question: "A watchdog timer helps by:",
    choices: [
      "Resetting the system if software hangs",
      "Encrypting firmware",
      "Increasing RAM",
      "Removing interrupts",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg330-17",
    courseCode: "CPEG330",
    question: "Bootloader is responsible for:",
    choices: [
      "Loading/starting firmware (and often enabling updates)",
      "Analog filtering",
      "Power conversion",
      "Sensor fusion",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg330-18",
    courseCode: "CPEG330",
    question: "When interfacing a 5V sensor to a 3.3V MCU, you often need:",
    choices: ["Level shifting", "Overclocking", "More cache", "A bigger monitor"],
    correctIndex: 0,
  },
  {
    id: "cpeg330-19",
    courseCode: "CPEG330",
    question: "A common reason to use interrupts instead of polling is:",
    choices: [
      "Better responsiveness and lower CPU waste",
      "More delay",
      "Less efficiency",
      "No need for timing",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg330-20",
    courseCode: "CPEG330",
    question: "A crystal oscillator is mainly used for:",
    choices: [
      "Accurate clock generation",
      "Analog voltage regulation",
      "Data encryption",
      "Motor actuation",
    ],
    correctIndex: 0,
  },

  /* ============================== CPEG340 (20) ============================== */
  {
    id: "cpeg340-1",
    courseCode: "CPEG340",
    question: "An embedded system is best described as:",
    choices: [
      "A computer designed for a dedicated function within a larger system",
      "A general-purpose gaming PC",
      "A cloud server only",
      "A database application only",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-2",
    courseCode: "CPEG340",
    question: "A real-time system is one where correctness depends on:",
    choices: [
      "Only logical results",
      "Timing constraints as well as logical results",
      "Network speed only",
      "Screen resolution",
    ],
    correctIndex: 1,
  },
  {
    id: "cpeg340-3",
    courseCode: "CPEG340",
    question: "Hard real-time means:",
    choices: [
      "Deadlines are strict; missing can cause failure",
      "Deadlines are optional",
      "Tasks never run",
      "Only battery operation",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-4",
    courseCode: "CPEG340",
    question: "A common embedded design flow is:",
    choices: [
      "Requirements → design → implementation → testing",
      "Testing → requirements → design",
      "Shipping → design later",
      "Ignore constraints",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-5",
    courseCode: "CPEG340",
    question: "Power optimization often involves:",
    choices: [
      "Sleep modes and duty cycling",
      "Always running CPU at max frequency",
      "Removing sensors",
      "Increasing heat",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-6",
    courseCode: "CPEG340",
    question: "An RTOS provides:",
    choices: [
      "Task scheduling and synchronization primitives",
      "A bigger screen",
      "Extra disk space",
      "Only graphics drivers",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-7",
    courseCode: "CPEG340",
    question: "A semaphore is typically used for:",
    choices: [
      "Synchronization / controlling access to resources",
      "Analog filtering",
      "Clock generation",
      "Compression",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-8",
    courseCode: "CPEG340",
    question: "A mutex is used to:",
    choices: [
      "Protect shared resources from concurrent access",
      "Increase battery voltage",
      "Decode video",
      "Generate PWM",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-9",
    courseCode: "CPEG340",
    question: "Priority inversion can occur when:",
    choices: [
      "A high-priority task waits on a lock held by a low-priority task",
      "All tasks have the same priority",
      "There is no shared data",
      "No interrupts exist",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-10",
    courseCode: "CPEG340",
    question: "A common technique to handle priority inversion is:",
    choices: [
      "Priority inheritance",
      "Disable all scheduling forever",
      "Remove locks entirely",
      "Only polling",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-11",
    courseCode: "CPEG340",
    question: "A finite state machine (FSM) is useful for:",
    choices: [
      "Modeling event-driven embedded behavior",
      "Increasing RAM",
      "Designing fonts",
      "Storing images",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-12",
    courseCode: "CPEG340",
    question: "In sensor systems, sampling rate should be chosen based on:",
    choices: [
      "Signal bandwidth (Nyquist idea)",
      "Screen size",
      "Battery brand",
      "Number of buttons",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-13",
    courseCode: "CPEG340",
    question: "A low-pass filter is commonly used to:",
    choices: [
      "Reduce high-frequency noise",
      "Increase noise",
      "Convert digital to analog",
      "Generate interrupts",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-14",
    courseCode: "CPEG340",
    question: "An embedded “watchdog” is important because it:",
    choices: [
      "Recovers the system from hangs by reset",
      "Stores logs",
      "Upscales video",
      "Increases CPU core count",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-15",
    courseCode: "CPEG340",
    question: "A good embedded logging strategy in production is to:",
    choices: [
      "Log key events with minimal overhead (and rotate/limit size)",
      "Print everything at max rate always",
      "Disable error logs",
      "Store logs only in volatile RAM",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-16",
    courseCode: "CPEG340",
    question: "Over-the-air (OTA) updates require special care mainly for:",
    choices: [
      "Reliability and rollback safety",
      "More UI animations",
      "Higher screen brightness",
      "Bigger keyboard",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-17",
    courseCode: "CPEG340",
    question: "A common communication pattern in embedded systems is:",
    choices: [
      "Producer/consumer with a queue",
      "Only global variables",
      "Only recursion",
      "Only busy-wait loops",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-18",
    courseCode: "CPEG340",
    question: "A queue in an RTOS is used to:",
    choices: [
      "Pass messages/data between tasks safely",
      "Boost voltage",
      "Increase clock accuracy",
      "Encrypt flash",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-19",
    courseCode: "CPEG340",
    question: "“Fail-safe” design means the system should:",
    choices: [
      "Enter a safe state when something goes wrong",
      "Always continue operation even if dangerous",
      "Ignore sensor errors",
      "Disable testing",
    ],
    correctIndex: 0,
  },
  {
    id: "cpeg340-20",
    courseCode: "CPEG340",
    question: "Why do embedded systems often avoid dynamic memory allocation?",
    choices: [
      "To reduce fragmentation and timing unpredictability",
      "Because it increases safety always",
      "Because it improves graphics",
      "Because it makes code shorter",
    ],
    correctIndex: 0,
  },
];
